<?php

namespace Arbor\Resource\UkDfe;

class ResourceType
{
    public const UK_DFE_EDUCATIONAL_INSTITUTION = 'UkDfe_EducationalInstitution';
    public const UK_DFE_EDUCATIONAL_INSTITUTION_ENROLMENT = 'UkDfe_EducationalInstitutionEnrolment';
    public const UK_DFE_STAFF = 'UkDfe_Staff';
    public const UK_DFE_STUDENT = 'UkDfe_Student';
    public const UK_DFE_UPN_ASSIGNMENT = 'UkDfe_UpnAssignment';
    public const UK_DFE_LOCAL_AUTHORITY = 'UkDfe_LocalAuthority';
    public const UK_DFE_SCHOOL_WORKFORCE_CENSUS = 'UkDfe_SchoolWorkforceCensus';
    public const UK_DFE_SCHOOL_WORKFORCE_CENSUS_RETURN = 'UkDfe_SchoolWorkforceCensusReturn';
    public const UK_DFE_PAY_SCALE = 'UkDfe_PayScale';
    public const UK_DFE_POSITION = 'UkDfe_Position';
    public const UK_DFE_LANGUAGE = 'UkDfe_Language';
    public const UK_DFE_RELIGION = 'UkDfe_Religion';
    public const UK_DFE_ETHNICITY = 'UkDfe_Ethnicity';
    public const UK_DFE_GUARDIAN_RELATIONSHIP_TYPE = 'UkDfe_GuardianRelationshipType';
    public const UK_DFE_SEN_STATUS = 'UkDfe_SenStatus';
    public const UK_DFE_SEN_NEED_TYPE = 'UkDfe_SenNeedType';
    public const UK_DFE_UNENROLMENT_REASON = 'UkDfe_UnenrolmentReason';
    public const UK_DFE_CENSUS_SCHOOL_PHASE = 'UkDfe_CensusSchoolPhase';
    public const UK_DFE_SCHOOL_GOVERNANCE_TYPE = 'UkDfe_SchoolGovernanceType';
    public const UK_DFE_SCHOOL_INTAKE_TYPE = 'UkDfe_SchoolIntakeType';
    public const UK_DFE_SCHOOL_TYPE = 'UkDfe_SchoolType';
    public const UK_DFE_SCHOOL_WORKFORCE_VACANCY_POST = 'UkDfe_SchoolWorkforceVacancyPost';
    public const UK_DFE_QUALIFIED_TEACHER_ROUTE = 'UkDfe_QualifiedTeacherRoute';
    public const UK_DFE_PAY_SCALE_CATEGORY = 'UkDfe_PayScaleCategory';
    public const UK_DFE_POSITION_CATEGORY = 'UkDfe_PositionCategory';
    public const UK_DFE_CURRICULUM_GRADE = 'UkDfe_CurriculumGrade';
    public const UK_DFE_SUBJECT = 'UkDfe_Subject';
    public const UK_DFE_SCHOOL_CENSUS = 'UkDfe_SchoolCensus';
    public const UK_DFE_SCHOOL_CENSUS_SCHOOL_DETAIL = 'UkDfe_SchoolCensusSchoolDetail';
    public const UK_DFE_SCHOOL_CENSUS_RETURN = 'UkDfe_SchoolCensusReturn';
    public const UK_DFE_SCHOOL_CENSUS_CLASS = 'UkDfe_SchoolCensusClass';
    public const UK_DFE_CHILD_PROTECTION_STATUS_ASSIGNMENT = 'UkDfe_ChildProtectionStatusAssignment';
    public const UK_DFE_IN_CARE_STATUS_ASSIGNMENT = 'UkDfe_InCareStatusAssignment';
    public const UK_DFE_TRAVELLER_STATUS = 'UkDfe_TravellerStatus';
    public const UK_DFE_TRAVELLER_STATUS_ASSIGNMENT = 'UkDfe_TravellerStatusAssignment';
    public const UK_DFE_ENROLMENT_MODE = 'UkDfe_EnrolmentMode';
    public const UK_DFE_SCHOOL_CENSUS_PUPIL_RECONCILIATION = 'UkDfe_SchoolCensusPupilReconciliation';
    public const UK_DFE_SEN_STATUS_ASSIGNMENT = 'UkDfe_SenStatusAssignment';
    public const UK_DFE_EXCLUSION_REASON = 'UkDfe_ExclusionReason';
    public const UK_DFE_ACADEMIC_YEAR_ENROLMENT = 'UkDfe_AcademicYearEnrolment';
    public const UK_DFE_SERVICE_CHILD_STATUS_ASSIGNMENT = 'UkDfe_ServiceChildStatusAssignment';
    public const UK_DFE_PROGRAMME = 'UkDfe_Programme';
    public const UK_DFE_PROGRAMME_INSTANCE = 'UkDfe_ProgrammeInstance';
    public const UK_DFE_PROGRAMME_ENROLMENT = 'UkDfe_ProgrammeEnrolment';
    public const UK_DFE_CHILD_CARE_PLACE = 'UkDfe_ChildCarePlace';
    public const UK_DFE_EARLY_YEARS_PUPIL_PREMIUM_ELIGIBILITY = 'UkDfe_EarlyYearsPupilPremiumEligibility';
    public const UK_DFE_EARLY_YEARS_PUPIL_PREMIUM_RECIPIENT = 'UkDfe_EarlyYearsPupilPremiumRecipient';
    public const UK_DFE_ENGLISH_PROFICIENCY = 'UkDfe_EnglishProficiency';
    public const UK_DFE_OFSTED_GRADE = 'UkDfe_OfstedGrade';
    public const UK_DFE_SCHOOL_WORKFORCE_CENSUS_STAFF_INFORMATION = 'UkDfe_SchoolWorkforceCensusStaffInformation';
    public const UK_DFE_SCHOOL_WORKFORCE_CENSUS_VACANCY = 'UkDfe_SchoolWorkforceCensusVacancy';
    public const UK_DFE_SCHOOL_WORKFORCE_CENSUS_AGENCY_TP_SUPPORT_COUNT = 'UkDfe_SchoolWorkforceCensusAgencyTpSupportCount';
    public const UK_DFE_STUDENT_FUNDING_TYPE = 'UkDfe_StudentFundingType';
    public const UK_DFE_TWO_YEAR_OLD_FUNDING_BASIS = 'UkDfe_TwoYearOldFundingBasis';
    public const UK_DFE_PUPIL_PREMIUM_RECIPIENT = 'UkDfe_PupilPremiumRecipient';
    public const UK_DFE_PUPIL_PREMIUM_RECIPIENT_TYPE = 'UkDfe_PupilPremiumRecipientType';
    public const UK_DFE_SERVICE_CHILD_CONCERN = 'UkDfe_ServiceChildConcern';
    public const UK_DFE_GCSE_ENGLISH_ACHIEVEMENT_TYPE = 'UkDfe_GcseEnglishAchievementType';
    public const UK_DFE_GCSE_ENGLISH_FUNDING_EXEMPTION_TYPE = 'UkDfe_GcseEnglishFundingExemptionType';
    public const UK_DFE_GCSE_MATHS_ACHIEVEMENT_TYPE = 'UkDfe_GcseMathsAchievementType';
    public const UK_DFE_GCSE_MATHS_FUNDING_EXEMPTION_TYPE = 'UkDfe_GcseMathsFundingExemptionType';
    public const UK_DFE_UCAS_IMPORT = 'UkDfe_UcasImport';
    public const UK_DFE_UCAS_IMPORT_RECORD = 'UkDfe_UcasImportRecord';
    public const UK_DFE_ATTENDANCE_API_SUBMISSION = 'UkDfe_AttendanceApiSubmission';
    public const UK_DFE_ALTERNATIVE_PROVISION_REASON = 'UkDfe_AlternativeProvisionReason';
    public const UK_DFE_ALTERNATIVE_PROVISION_PLACEMENT_REASON = 'UkDfe_AlternativeProvisionPlacementReason';
    public const UK_DFE_ALTERNATIVE_PROVISION_PLACEMENT = 'UkDfe_AlternativeProvisionPlacement';
    public const UK_DFE_PERMANENT_EXCLUSION = 'UkDfe_PermanentExclusion';
    public const UK_DFE_ACADEMIC_UNIT_ENROLMENT = 'UkDfe_AcademicUnitEnrolment';
    public const UK_DFE_SCHOOL_LED_TUTORING_HOUR = 'UkDfe_SchoolLedTutoringHour';
    public const UK_DFE_YOUNG_CARER_STATUS_ASSIGNMENT = 'UkDfe_YoungCarerStatusAssignment';
}
