<?php

namespace Arbor\Resource\UkDfe;

class ResourceType
{
	const UK_DFE_EDUCATIONAL_INSTITUTION = 'UkDfe_EducationalInstitution';
	const UK_DFE_EDUCATIONAL_INSTITUTION_ENROLMENT = 'UkDfe_EducationalInstitutionEnrolment';
	const UK_DFE_STAFF = 'UkDfe_Staff';
	const UK_DFE_STUDENT = 'UkDfe_Student';
	const UK_DFE_UPN_ASSIGNMENT = 'UkDfe_UpnAssignment';
	const UK_DFE_LOCAL_AUTHORITY = 'UkDfe_LocalAuthority';
	const UK_DFE_SCHOOL_WORKFORCE_CENSUS = 'UkDfe_SchoolWorkforceCensus';
	const UK_DFE_SCHOOL_WORKFORCE_CENSUS_RETURN = 'UkDfe_SchoolWorkforceCensusReturn';
	const UK_DFE_PAY_SCALE = 'UkDfe_PayScale';
	const UK_DFE_POSITION = 'UkDfe_Position';
	const UK_DFE_LANGUAGE = 'UkDfe_Language';
	const UK_DFE_RELIGION = 'UkDfe_Religion';
	const UK_DFE_ETHNICITY = 'UkDfe_Ethnicity';
	const UK_DFE_GUARDIAN_RELATIONSHIP_TYPE = 'UkDfe_GuardianRelationshipType';
	const UK_DFE_SEN_STATUS = 'UkDfe_SenStatus';
	const UK_DFE_SEN_NEED_TYPE = 'UkDfe_SenNeedType';
	const UK_DFE_UNENROLMENT_REASON = 'UkDfe_UnenrolmentReason';
	const UK_DFE_CENSUS_SCHOOL_PHASE = 'UkDfe_CensusSchoolPhase';
	const UK_DFE_SCHOOL_GOVERNANCE_TYPE = 'UkDfe_SchoolGovernanceType';
	const UK_DFE_SCHOOL_INTAKE_TYPE = 'UkDfe_SchoolIntakeType';
	const UK_DFE_SCHOOL_TYPE = 'UkDfe_SchoolType';
	const UK_DFE_SCHOOL_WORKFORCE_VACANCY_POST = 'UkDfe_SchoolWorkforceVacancyPost';
	const UK_DFE_QUALIFIED_TEACHER_ROUTE = 'UkDfe_QualifiedTeacherRoute';
	const UK_DFE_PAY_SCALE_CATEGORY = 'UkDfe_PayScaleCategory';
	const UK_DFE_POSITION_CATEGORY = 'UkDfe_PositionCategory';
	const UK_DFE_CURRICULUM_GRADE = 'UkDfe_CurriculumGrade';
	const UK_DFE_SUBJECT = 'UkDfe_Subject';
	const UK_DFE_SCHOOL_CENSUS = 'UkDfe_SchoolCensus';
	const UK_DFE_SCHOOL_CENSUS_SCHOOL_DETAIL = 'UkDfe_SchoolCensusSchoolDetail';
	const UK_DFE_SCHOOL_CENSUS_RETURN = 'UkDfe_SchoolCensusReturn';
	const UK_DFE_SCHOOL_CENSUS_CLASS = 'UkDfe_SchoolCensusClass';
	const UK_DFE_CHILD_PROTECTION_STATUS_ASSIGNMENT = 'UkDfe_ChildProtectionStatusAssignment';
	const UK_DFE_IN_CARE_STATUS_ASSIGNMENT = 'UkDfe_InCareStatusAssignment';
	const UK_DFE_TRAVELLER_STATUS = 'UkDfe_TravellerStatus';
	const UK_DFE_TRAVELLER_STATUS_ASSIGNMENT = 'UkDfe_TravellerStatusAssignment';
	const UK_DFE_ENROLMENT_MODE = 'UkDfe_EnrolmentMode';
	const UK_DFE_SCHOOL_CENSUS_PUPIL_RECONCILIATION = 'UkDfe_SchoolCensusPupilReconciliation';
	const UK_DFE_SEN_STATUS_ASSIGNMENT = 'UkDfe_SenStatusAssignment';
	const UK_DFE_EXCLUSION_REASON = 'UkDfe_ExclusionReason';
	const UK_DFE_ACADEMIC_YEAR_ENROLMENT = 'UkDfe_AcademicYearEnrolment';
	const UK_DFE_SERVICE_CHILD_STATUS_ASSIGNMENT = 'UkDfe_ServiceChildStatusAssignment';
	const UK_DFE_PROGRAMME = 'UkDfe_Programme';
	const UK_DFE_PROGRAMME_INSTANCE = 'UkDfe_ProgrammeInstance';
	const UK_DFE_PROGRAMME_ENROLMENT = 'UkDfe_ProgrammeEnrolment';
	const UK_DFE_CHILD_CARE_PLACE = 'UkDfe_ChildCarePlace';
	const UK_DFE_EARLY_YEARS_PUPIL_PREMIUM_ELIGIBILITY = 'UkDfe_EarlyYearsPupilPremiumEligibility';
	const UK_DFE_EARLY_YEARS_PUPIL_PREMIUM_RECIPIENT = 'UkDfe_EarlyYearsPupilPremiumRecipient';
	const UK_DFE_ENGLISH_PROFICIENCY = 'UkDfe_EnglishProficiency';
	const UK_DFE_OFSTED_GRADE = 'UkDfe_OfstedGrade';
	const UK_DFE_SCHOOL_WORKFORCE_CENSUS_STAFF_INFORMATION = 'UkDfe_SchoolWorkforceCensusStaffInformation';
	const UK_DFE_SCHOOL_WORKFORCE_CENSUS_VACANCY = 'UkDfe_SchoolWorkforceCensusVacancy';
	const UK_DFE_SCHOOL_WORKFORCE_CENSUS_AGENCY_TP_SUPPORT_COUNT = 'UkDfe_SchoolWorkforceCensusAgencyTpSupportCount';
	const UK_DFE_STUDENT_FUNDING_TYPE = 'UkDfe_StudentFundingType';
	const UK_DFE_TWO_YEAR_OLD_FUNDING_BASIS = 'UkDfe_TwoYearOldFundingBasis';
	const UK_DFE_PUPIL_PREMIUM_RECIPIENT = 'UkDfe_PupilPremiumRecipient';
	const UK_DFE_PUPIL_PREMIUM_RECIPIENT_TYPE = 'UkDfe_PupilPremiumRecipientType';
	const UK_DFE_SERVICE_CHILD_CONCERN = 'UkDfe_ServiceChildConcern';
	const UK_DFE_GCSE_ENGLISH_ACHIEVEMENT_TYPE = 'UkDfe_GcseEnglishAchievementType';
	const UK_DFE_GCSE_ENGLISH_FUNDING_EXEMPTION_TYPE = 'UkDfe_GcseEnglishFundingExemptionType';
	const UK_DFE_GCSE_MATHS_ACHIEVEMENT_TYPE = 'UkDfe_GcseMathsAchievementType';
	const UK_DFE_GCSE_MATHS_FUNDING_EXEMPTION_TYPE = 'UkDfe_GcseMathsFundingExemptionType';
	const UK_DFE_UCAS_IMPORT = 'UkDfe_UcasImport';
	const UK_DFE_UCAS_IMPORT_RECORD = 'UkDfe_UcasImportRecord';
	const UK_DFE_ATTENDANCE_API_SUBMISSION = 'UkDfe_AttendanceApiSubmission';
	const UK_DFE_ALTERNATIVE_PROVISION_REASON = 'UkDfe_AlternativeProvisionReason';
	const UK_DFE_ALTERNATIVE_PROVISION_PLACEMENT_REASON = 'UkDfe_AlternativeProvisionPlacementReason';
	const UK_DFE_ALTERNATIVE_PROVISION_PLACEMENT = 'UkDfe_AlternativeProvisionPlacement';
	const UK_DFE_PERMANENT_EXCLUSION = 'UkDfe_PermanentExclusion';
	const UK_DFE_ACADEMIC_UNIT_ENROLMENT = 'UkDfe_AcademicUnitEnrolment';
	const UK_DFE_SCHOOL_LED_TUTORING_HOUR = 'UkDfe_SchoolLedTutoringHour';
	const UK_DFE_YOUNG_CARER_STATUS_ASSIGNMENT = 'UkDfe_YoungCarerStatusAssignment';
}
