name: "Secret Scanner"
on:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  secrets-scanner:
    uses: arbor-education/gha.workflows/.github/workflows/secret-scanner-template.yaml@DOPS-12604-cicd-scanner
    secrets:
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
